language: objective-c

before_install: 
  - brew update
  - brew install xctool

script: xctool -reporter pretty -project iOShoppingCart.xcodeproj -sdk iphonesimulator -scheme iOShoppingCart build test
